const icondata = {
    color: {
        name: 'color',
        dis: '基础色彩 $gray $green $red $orange $blue按照$-light,$-dark分为2个级别，$gray 会衍生更多级别（-dark,-' +
                'darker,-darkest,-light,-lighter,-lightest）',
        data: [
            {
                name: '$gray-lightest',
                type: 0,
                dis: null,
                class: '.gray-lightest'
            }, {
                name: '$gray-lighter',
                type: 0,
                dis: null,
                class: '.gray-lighter'
            }, {
                name: '$gray-light',
                type: 0,
                dis: null,
                class: '.gray-light'
            }, {
                name: '$gray',
                type: 0,
                dis: null,
                class: '.gray'
            }, {
                name: '$gray-dark',
                type: 0,
                dis: null,
                class: '.gray-dark'
            }, {
                name: '$gray-darker',
                type: 0,
                dis: null,
                class: '.gray-darker'
            }, {
                name: '$gray-darkest',
                type: 0,
                dis: null,
                class: '.gray-darkest'
            }, {
                name: '',
                type: 0,
                dis: null,
                class: ''
            }, {
                name: '',
                type: 0,
                dis: null,
                class: ''
            }, {
                name: '$green-light',
                type: 0,
                dis: null,
                class: '.green-light'
            }, {
                name: '$green',
                type: 0,
                dis: null,
                class: '.green'
            }, {
                name: '$green-dark',
                type: 0,
                dis: null,
                class: '.green-dark'
            }, {
                name: '$red-light',
                type: 0,
                dis: null,
                class: '.red-light'
            }, {
                name: '$red',
                type: 0,
                dis: null,
                class: '.red'
            }, {
                name: '$red-dark',
                type: 0,
                dis: null,
                class: '.red-dark'
            }, {
                name: '$orange-light',
                type: 0,
                dis: null,
                class: '.orange-light'
            }, {
                name: '$orange',
                type: 0,
                dis: null,
                class: '.orange'
            }, {
                name: '$orange-dark',
                type: 0,
                dis: null,
                class: '.orange-dark'
            }, {
                name: '$blue-light',
                type: 0,
                dis: null,
                class: '.blue-light'
            }, {
                name: '$blue',
                type: 0,
                dis: null,
                class: '.blue'
            }, {
                name: '$blue-dark',
                type: 0,
                dis: null,
                class: '.blue-dark'
            }, {
                name: '.white',
                type: 1,
                dis: null,
                class: '.white'
            }, {
                name: '.gray-lightest',
                type: 1,
                dis: null,
                class: '.gray-lightest'
            }, {
                name: '.gray-lighter',
                type: 1,
                dis: null,
                class: '.gray-lighter'
            }, {
                name: '.gray-light',
                type: 1,
                dis: null,
                class: '.gray-light'
            }, {
                name: '.gray',
                type: 1,
                dis: null,
                class: '.gray'
            }, {
                name: '.gray-dark',
                type: 1,
                dis: null,
                class: '.gray-dark'
            }, {
                name: '.gray-darker',
                type: 1,
                dis: null,
                class: '.gray-darker'
            }, {
                name: '.gray-darkest',
                type: 1,
                dis: null,
                class: '.gray-darkest'
            }, {
                name: '.black',
                type: 1,
                dis: null,
                class: '.black'
            }, {
                name: '.green-light',
                type: 1,
                dis: null,
                class: '.green-light'
            }, {
                name: '.green',
                type: 1,
                dis: null,
                class: '.green'
            }, {
                name: '.green-dark',
                type: 1,
                dis: null,
                class: '.green-dark'
            }, {
                name: '.red-light',
                type: 1,
                dis: null,
                class: '.red-light'
            }, {
                name: '.red',
                type: 1,
                dis: null,
                class: '.red'
            }, {
                name: '.red-dark',
                type: 1,
                dis: null,
                class: '.red-dark'
            }, {
                name: '.orange-light',
                type: 1,
                dis: null,
                class: '.orange-light'
            }, {
                name: '.orange',
                type: 1,
                dis: null,
                class: '.orange'
            }, {
                name: '.orange-dark',
                type: 1,
                dis: null,
                class: '.orange-dark'
            }, {
                name: '.blue-light',
                type: 1,
                dis: null,
                class: '.blue-light'
            }, {
                name: '.blue',
                type: 1,
                dis: null,
                class: '.blue'
            }, {
                name: '.blue-dark',
                type: 1,
                dis: null,
                class: '.blue-dark'
            }
        ]
    },
    fontSize: {
        name: 'fontSize',
        dis: '($font,.font)按照大小分为6个级别（-big,-bigger,-biggest,-small,-smaller,-smallest）',
        data: [
            {
                name: '$font-smallest',
                type: 0,
                dis: '16px',
                class: 'font-smallest'
            }, {
                name: '$font-smaller',
                type: 0,
                dis: '18px',
                class: 'font-smaller'
            }, {
                name: '$font-small',
                type: 0,
                dis: '20px',
                class: 'font-small'
            }, {
                name: '$font',
                type: 0,
                dis: '24px',
                class: 'font'
            }, {
                name: '$font-big',
                type: 0,
                dis: '28px',
                class: 'font-big'
            }, {
                name: '$font-bigger',
                type: 0,
                dis: '30px',
                class: 'font-bigger'
            }, {
                name: '$font-biggest',
                type: 0,
                dis: '36px',
                class: 'font-biggest'
            }, {
                name: '.font-smallest',
                type: 1,
                dis: '16px',
                class: 'font-smallest'
            }, {
                name: '.font-smaller',
                type: 1,
                dis: '18px',
                class: 'font-smaller'
            }, {
                name: 'font-small',
                type: 1,
                dis: '20px',
                class: 'font-small'
            }, {
                name: '.font',
                type: 1,
                dis: '24px',
                class: 'font'
            }, {
                name: '.font-big',
                type: 1,
                dis: '28px',
                class: 'font-big'
            }, {
                name: '.font-bigger',
                type: 1,
                dis: '30px',
                class: 'font-bigger'
            }, {
                name: '.font-biggest',
                type: 1,
                dis: '36px',
                class: 'font-biggest'
            }
        ]
    }
};

export default icondata;
