const icondata = [
    {
        name: 'icon-arrow-down'
    }, {
        name: 'icon-arrow-left'
    }, {
        name: 'icon-arrow-right'
    }, {
        name: 'icon-arrow-up'
    }, {
        name: 'icon-back'
    }, {
        name: 'icon-bag-a'
    }, {
        name: 'icon-bag-b'
    }, {
        name: 'icon-bag-c'
    }, {
        name: 'icon-bottle-a'
    }, {
        name: 'icon-bottle-b'
    }, {
        name: 'icon-bottle-c'
    }, {
        name: 'icon-bottle-d'
    }, {
        name: 'icon-cake'
    }, {
        name: 'icon-calendar'
    }, {
        name: 'icon-card'
    }, {
        name: 'icon-cart-a'
    }, {
        name: 'icon-cart-b'
    }, {
        name: 'icon-clock'
    }, {
        name: 'icon-close-a'
    }, {
        name: 'icon-close-b'
    }, {
        name: 'icon-coin-a'
    }, {
        name: 'icon-coin-b'
    }, {
        name: 'icon-coin-c'
    }, {
        name: 'icon-coin-d'
    }, {
        name: 'icon-coin-e'
    }, {
        name: 'icon-coin-f'
    }, {
        name: 'icon-crown'
    }, {
        name: 'icon-diamonds'
    }, {
        name: 'icon-down-b'
    }, {
        name: 'icon-edit-a'
    }, {
        name: 'icon-edit-b'
    }, {
        name: 'icon-factory'
    }, {
        name: 'icon-female'
    }, {
        name: 'icon-fold'
    }, {
        name: 'icon-game'
    }, {
        name: 'icon-gift-a'
    }, {
        name: 'icon-gift-b'
    }, {
        name: 'icon-gift-c'
    }, {
        name: 'icon-gnqbj'
    }, {
        name: 'icon-gzss'
    }, {
        name: 'icon-heart-a'
    }, {
        name: 'icon-heart-b'
    }, {
        name: 'icon-home-a'
    }, {
        name: 'icon-home-b'
    }, {
        name: 'icon-jfss'
    }, {
        name: 'icon-jkjc'
    }, {
        name: 'icon-key'
    }, {
        name: 'icon-kjl'
    }, {
        name: 'icon-location'
    }, {
        name: 'icon-lock-a'
    }, {
        name: 'icon-lock-b'
    }, {
        name: 'icon-lock'
    }, {
        name: 'icon-male'
    }, {
        name: 'icon-minus'
    }, {
        name: 'icon-more-a'
    }, {
        name: 'icon-more-b'
    }, {
        name: 'icon-mrmy'
    }, {
        name: 'icon-notebook-a'
    }, {
        name: 'icon-notebook-b'
    }, {
        name: 'icon-notebook-c'
    }, {
        name: 'icon-package'
    }, {
        name: 'icon-people'
    }, {
        name: 'icon-phone'
    }, {
        name: 'icon-plus'
    }, {
        name: 'icon-praise-a'
    }, {
        name: 'icon-praise-b'
    }, {
        name: 'icon-praise-c'
    }, {
        name: 'icon-qlxjk'
    }, {
        name: 'icon-record-a'
    }, {
        name: 'icon-record-b'
    }, {
        name: 'icon-record-c'
    }, {
        name: 'icon-right-b'
    }, {
        name: 'icon-scancode'
    }, {
        name: 'icon-search-a'
    }, {
        name: 'icon-selected'
    }, {
        name: 'icon-setting'
    }, {
        name: 'icon-smzl'
    }, {
        name: 'icon-star-a'
    }, {
        name: 'icon-star-b'
    }, {
        name: 'icon-store-a'
    }, {
        name: 'icon-store'
    }, {
        name: 'icon-tag-a'
    }, {
        name: 'icon-tag-b'
    }, {
        name: 'icon-tag'
    }, {
        name: 'icon-talk-a'
    }, {
        name: 'icon-talk-b'
    }, {
        name: 'icon-tick-c'
    }, {
        name: 'icon-ticket-a'
    }, {
        name: 'icon-ticket-b'
    }, {
        name: 'icon-tjnfb'
    }, {
        name: 'icon-tnb'
    }, {
        name: 'icon-type'
    }, {
        name: 'icon-unfold'
    }, {
        name: 'icon-up-b'
    }, {
        name: 'icon-user-a'
    }, {
        name: 'icon-user-b'
    }, {
        name: 'icon-userinfo'
    }, {
        name: 'icon-voice-a'
    }, {
        name: 'icon-voice-b'
    }, {
        name: 'icon-voice-c'
    }, {
        name: 'icon-xxgjb'
    }, {
        name: 'icon-zfg'
    }, {
        name: 'icon-zqmyl'
    }, {
        name: 'icon-truck'
    }
];

export default icondata;
