// Posts
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE';

// Single Post
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE';

// atest
export const CHANGE_COUNTER_STEP = 'CHANGE_COUNTER_STEP';
export const TICK_COUNTER = 'TICK_COUNTER';
export const START_COUNTER = 'START_COUNTER';
export const STOP_COUNTER = 'STOP_COUNTER';
